<a href="https://colab.research.google.com/github/urfavnada/Beginner/blob/main/Candy_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project: cleanning - [candy data]
### this notebook is for educational purpose . in this notebook we will do some cleanning

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">wrangling</a></li>
  
</ul>

<a id='intro'></a>
## Introduction

### Dataset Description

> i will go through candy data 2017 , this data has :
- Internal_ID
- Q1-Going Out?: Are you actually going trick or treating yourself? "has values `Yes or No`"
- Q2-Gender: It has four different options, `Femal ,Male ,Other ,I'd rather not say`
- Q3-Age: Numerical field
- Q4-Country: Text Field, but users have written their own version of the names. Example, for America, there are entries such as USA, us, US, America so we should consider that while cleanning
- Q5-State/Province: Text Field, but users have written their own version of the names. Same as the country data.
- Q6-Joy Or Despair: All kinds of chocolate bars are the questions with three distinct options to choose from (Joy, Meh, Despair).
- Q7-Joy Other: Text Field to write items not included above that give you JOY. Lots of missing values.
- Q8-Despair Other: Text Field ti write items not included above that give you DESPAIR. Lots of missing values.
- Q9-Other Comments: Text Field. Lots of missing values.
- Q10-Dress: Binary field. Missing values present
- Unnamed: 113
- Q11-Day: Binary Answer Field. Missing values present


# 1- import packages and load data

In [33]:
# importing libararies
import pandas as pd
import numpy as np
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') # ignore warnings.
df = pd.read_excel("candyhierarchy2017.xlsx")
df.shape

(2460, 120)

<a id='wrangling'></a>
## Data Wrangling



### General Properties

# 2- show some general properties for the data

In [2]:
pd.set_option('display.max_columns',120)
df.head()

Internal ID Q1: GOING OUT? Q2: GENDER Q3: AGE Q4: COUNTRY  \
0     90258773            NaN        NaN     NaN         NaN   
1     90272821             No       Male      44        USA    
2     90272829            NaN       Male      49         USA   
3     90272840             No       Male      40          us   
4     90272841             No       Male      23         usa   

  Q5: STATE, PROVINCE, COUNTY, ETC Q6 | 100 Grand Bar  \
0                              NaN                NaN   
1                               NM                MEH   
2                         Virginia                NaN   
3                               or                MEH   
4                         exton pa                JOY   

  Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
0                                                NaN                                       
1                                            DESPAIR                                       
2                                                NaN                                       
3                                            DESPAIR                                       
4                                            DESPAIR                                       

  Q6 | Any full-sized candy bar Q6 | Black Jacks Q6 | Bonkers (the candy)  \
0                           NaN              NaN                      NaN   
1                           JOY              MEH                  DESPAIR   
2                           NaN              NaN                      NaN   
3                           JOY              MEH                      MEH   
4                           JOY          DESPAIR                      MEH   

  Q6 | Bonkers (the board game) Q6 | Bottle Caps Q6 | Box'o'Raisins  \
0                           NaN              NaN                NaN   
1                       DESPAIR          DESPAIR            DESPAIR   
2                           NaN              NaN                NaN   
3                       DESPAIR              MEH            DESPAIR   
4                       DESPAIR              MEH            DESPAIR   

  Q6 | Broken glow stick Q6 | Butterfinger Q6 | Cadbury Creme Eggs  \
0                    NaN               NaN                     NaN   
1                DESPAIR           DESPAIR                     MEH   
2                    NaN               NaN                     NaN   
3                DESPAIR               MEH                     MEH   
4                DESPAIR               MEH                     MEH   

  Q6 | Candy Corn  \
0             NaN   
1             MEH   
2             NaN   
3         DESPAIR   
4         DESPAIR   

  Q6 | Candy that is clearly just the stuff given out for free at restaurants  \
0                                                NaN                            
1                                            DESPAIR                            
2                                                NaN                            
3                                            DESPAIR                            
4                                            DESPAIR                            

  Q6 | Caramellos Q6 | Cash, or other forms of legal tender Q6 | Chardonnay  \
0             NaN                                       NaN             NaN   
1             MEH                                       JOY             MEH   
2             NaN                                       NaN             NaN   
3             MEH                                       JOY             MEH   
4             JOY                                       MEH             JOY   

  Q6 | Chick-o-Sticks (we don’t know what that is) Q6 | Chiclets  \
0                                              NaN           NaN   
1                                          DESPAIR       DESPAIR   
2                                              NaN           NaN   
3                                              JOY

In [3]:
df.isna().sum()

Internal ID                    0
Q1: GOING OUT?               110
Q2: GENDER                    41
Q3: AGE                       84
Q4: COUNTRY                   64
                            ... 
Q12: MEDIA [Daily Dish]     2375
Q12: MEDIA [Science]        1098
Q12: MEDIA [ESPN]           2361
Q12: MEDIA [Yahoo]          2393
Click Coordinates (x, y)     855
Length: 120, dtype: int64

In [4]:
df.iloc[:,0:50].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Data columns (total 50 columns):
 #   Column                                                                                 Non-Null Count  Dtype 
---  ------                                                                                 --------------  ----- 
 0   Internal ID                                                                            2460 non-null   int64 
 1   Q1: GOING OUT?                                                                         2350 non-null   object
 2   Q2: GENDER                                                                             2419 non-null   object
 3   Q3: AGE                                                                                2376 non-null   object
 4   Q4: COUNTRY                                                                            2396 non-null   object
 5   Q5: STATE, PROVINCE, COUNTY, ETC                                                   

# 3- write summary about what you get form the above functions
> #### tips : this summary can be about : if there is any missing values , if there a wrong data type , if there a wrong range of values , ....

In [5]:
# There are 108 columns about the chocolate kinds need to be cleaned
# there are some nan values
# There are some wrong data types

# cleaning

### 4- drop all the useless columns and  rows with too much NaN ,
> tip : useless columns can be like `Internal ID`and can be also columns with too much NaN
- rename columns for easy access

In [6]:
df.drop('Internal ID',axis=1,inplace=True)
df.drop('Unnamed: 113',axis=1,inplace=True)

### 5 - clean `going out` column
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [10]:
df["Q1: GOING OUT?"].isna().sum()
df["Q1: GOING OUT?"].fillna("unknown")

0       unknown
1            No
2       unknown
3            No
4            No
         ...   
2455         No
2456         No
2457         No
2458         No
2459         No
Name: Q1: GOING OUT?, Length: 2460, dtype: object

### 6 - clean ` gender` column
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [27]:
df["Q2: GENDER"].isna().sum()
df["Q2: GENDER"].unique()
df["Q2: GENDER"].fillna("Other")
df['Q2: GENDER'].replace("I'd rather not say",'Other',inplace=True)

### 7 - clean ` age` column
> tip : note the type of age column , and NaN values
 - try to use `to_numeric`
 - tip : you should choose which best value to put in place of these NaNs ( mean, median, ....etc)

In [21]:
df["Q3: AGE"].unique()
df["Q3: AGE"].replace(['Old enough','Many','?','no','45-55','312','hahahahaha','older than dirt','5u','Enough',
                       'See question 2','24-50','Over 50','1000','ancient','OLD','old','1','MY NAME JEFF',
                       '59 on the day after Halloween','old enough','your mom','4',
                       'I can remember when Java was a cool new language','60+','46 Halloweens.',
                      ' 1000'],np.nan,inplace=True)
df["Q3: AGE"].replace("sixty-nine",69,inplace=True)

In [24]:
pd.to_numeric(df['Q3: AGE'])
df['Q3: AGE'].describe()

count    2353.000000
mean       42.628517
std        23.847664
min         1.000000
25%        34.000000
50%        41.000000
75%        50.000000
max      1000.000000
Name: Q3: AGE, dtype: float64

In [25]:
df['Q3: AGE'].fillna(42.6)
df = df[df['Q3: AGE'] < 100]
df["Q3: AGE"].unique()

array([44. , 49. , 40. , 23. , 53. , 33. , 43. , 56. , 64. , 37. , 59. ,
       48. , 54. , 36. , 45. , 25. , 34. , 35. , 38. , 58. , 50. , 47. ,
       16. , 52. , 63. , 65. , 41. , 27. , 31. , 61. , 46. , 42. , 62. ,
       29. , 39. , 32. , 28. , 69. , 67. , 30. , 22. , 26. , 51. , 70. ,
       24. , 18. , 19. , 57. , 60. , 66. , 12. , 55. , 72. , 21. , 11. ,
        9. , 68. , 20. ,  6. , 10. , 71. , 90. , 13. , 99. ,  7. , 88. ,
       39.4, 74. , 17. , 15. ,  8. , 75. , 14. , 76. , 77. , 73. , 70.5,
        1. ,  4. ])

### 8 - clean ` country` column
> tip : note that country column has country names with different writing ways
  - use fuzzywuzzy to deal with this problem
  - you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [28]:
df["Q4: COUNTRY"].unique()

array(['USA ', 'USA', 'us', 'usa', 'canada', 'Canada', 'Us', nan, 'US',
       'Murica', 'United States', 'uk', 'United Kingdom', 'united states',
       'Usa', 'United States ', 'United staes',
       'United States of America', 'UAE', 'England', 'UK', 'canada ',
       'Mexico', 'United states', 'u.s.a.', 'USAUSAUSA', 'america',
       'france', 'United States of America ', 'U.S.A.', 'finland',
       'unhinged states', 'Canada ', 'united states of america',
       'US of A', 'Unites States', 'The United States', 'North Carolina ',
       'Unied States', 'Netherlands', 'germany', 'Europe', 'Earth', 'U S',
       'u.s.', 'U.K. ', 'Costa Rica', 'The United States of America',
       'unite states', 'U.S.', 'cascadia', 'Australia', 'Greece',
       'USA? Hard to tell anymore..', "'merica", 'usas', 'Pittsburgh',
       'United State', 'France', 'australia', 'Can', 'Canae', 'New York',
       'Trumpistan', 'Ireland', 'United Sates', 'Korea', 'California',
       'Japan', 'USa', 'South afr

In [34]:
df["Q4: COUNTRY"] = df["Q4: COUNTRY"].str.lower()
df["Q4: COUNTRY"] = df["Q4: COUNTRY"].str.strip()
df['Q4: COUNTRY'].replace(['canada','can','canae','canada`','soviet canuckistan'],"Canada", inplace = True)
df['Q4: COUNTRY'].unique()

array([nan, 'usa', 'us', 'Canada', 'murica', 'united states', 'uk',
       'united kingdom', 'united staes', 'united states of america',
       'uae', 'england', 'mexico', 'u.s.a.', 'usausausa', 'america',
       'france', 'finland', 'unhinged states', 'us of a', 'unites states',
       'the united states', 'north carolina', 'unied states',
       'netherlands', 'germany', 'europe', 'earth', 'u s', 'u.s.', 'u.k.',
       'costa rica', 'the united states of america', 'unite states',
       'cascadia', 'australia', 'insanity lately', 'greece',
       'usa? hard to tell anymore..', "'merica", 'usas', 'pittsburgh',
       'united state', 'a', 'new york', 'trumpistan', 'ireland',
       'united sates', 'korea', 'california', 'japan', 'south africa',
       'i pretend to be from canada, but i am really from the united states.',
       'iceland', 'scotland', 'denmark', 'united stated', 'switzerland',
       'ahem....amerca', 'ud', 'south korea', 'new jersey', 'indonesia',
       'united stste

In [49]:
df['Q4: COUNTRY'].replace(['united states','us','united staes','united states of america',
                          'uae','u.s.a.','usausausa','america','us of a','unites states','the united states','unied states',
                          'u s','u s','the united states of america','unite states','usa? hard to tell anymore..',
                          'usas','united state','united sates','i pretend to be from canada, but i am really from the united states.',
                          'united stated','united statss','united ststes','usaa','usa! usa! usa!','n. america','ussa',
                          'u s a','united statea','usa usa usa!!!!','usa','murica','unhinged states',
                          'u.s.',"'merica",'new york','new jersey','north carolina','costa rica','california',
                          'mexico','cascadia','pittsburgh','murrika','ahem....amerca','alaska'],'USA',inplace = True)
df["Q4: COUNTRY"].unique()


array([nan, 'USA', 'Canada', 'UK', 'EU', 'Australia', 'insanity lately',
       'a', 'Asia', 'South africa', 'scotland', 'atlantis',
       'subscribe to dm4uz3 on youtube', 'fear and loathing'],
      dtype=object)

In [45]:
df['Q4: COUNTRY'].replace(['canada','can','canae','canada`','soviet canuckistan'],"Canada", inplace = True)
df['Q4: COUNTRY'].replace(['uk','united kingdom','england','u.k.','ireland','ud','endland'],"UK", inplace = True)
df['Q4: COUNTRY'].unique()


array([nan, 'USA', 'Canada', 'UK', 'EU', 'Australia', 'insanity lately',
       'a', 'Asia', 'South africa', 'scotland', 'atlantis', 'alaska',
       'subscribe to dm4uz3 on youtube', 'fear and loathing'],
      dtype=object)

In [46]:
df['Q4: COUNTRY'].replace(['finland','europe','netherlands','germany','greece','iceland','denmark','switzerland',
                          'the netherlands','spain','sweden','france'],'EU', inplace = True)
df['Q4: COUNTRY'].replace(['korea','japan','indonesia','singapore',
                           'china','taiwan','hong kong','south korea'],"Asia" , inplace = True)
df['Q4: COUNTRY'].unique()

array([nan, 'USA', 'Canada', 'UK', 'EU', 'Australia', 'insanity lately',
       'a', 'Asia', 'South africa', 'scotland', 'atlantis', 'alaska',
       'subscribe to dm4uz3 on youtube', 'fear and loathing'],
      dtype=object)

In [52]:
df['Q4: COUNTRY'].replace('australia','Australia', inplace = True)
df['Q4: COUNTRY'].replace('south africa','South africa', inplace = True)
df['Q4: COUNTRY'].replace('scotland','Scotland', inplace = True)
df['Q4: COUNTRY'].replace(['earth','trumpistan','narnia',"i don't know anymore",'insanity lately','a','atlantis','subscribe to dm4uz3 on youtube','fear and loathing'],np.nan, inplace = True)
df['Q4: COUNTRY'].value_counts()


USA             2055
Canada           228
UK                40
EU                32
Asia              14
Australia          7
Scotland           5
South africa       1
Name: Q4: COUNTRY, dtype: int64

### 9 - clean ` area` column
> tip : area column has the same problem as country columns , but looking at all it's unique values may give us another way to deal with it rather than try to fix it

In [53]:
df["Q5: STATE, PROVINCE, COUNTY, ETC"].unique()

array([nan, 'NM', 'Virginia', 'or', 'exton pa', 'Colorado ', 'ontario',
       'Ontario', 'Wa', 'Quebec', 'NY', 'California', 'Texas', 'NEW YORK',
       'CO', 'IN', 'MN', 'aberdeenshire', 'Alberta', 'Wisconsin, 53705',
       'RI', 'NC', 'Scotland', 'minnesota', 'Michigan', 'Florida',
       'New Jersey', 'VA', 'Colorado', 'Los Angeles, California', 'CA',
       'New York ', 'Chicago, Illinois', 'Nj', 'Wisconsin', 'Minnesota ',
       'London', 'mn', 'TEXAS', 'Illinois', 'District of Columbia',
       'Washington', 'Massachusetts ', 'OR', 'Montana', 'New York',
       'massachusetts', 'Abu Dhabi', 'TX', 'Arizona', 'Dc', 'yukon',
       'Pennsylvania ', 'MD', 'Ohio', 'Alberta ', 'OXFORDSHIRE', 'DC',
       'Iowa', 'Mn', 'TN', 'BC', 'Maryland', 'MI', 'Wisconsin ', 'alaska',
       'Ny', 'Colorado, Jefferson county ', 'Louisiana', 'pa',
       'CO, Larimer County', 'Nebraska ', 'Oregon', 'UT', 'ny',
       'Pennsylvania', 'CDMX', 'north carolina', 'Tennessee ', 'Texas ',
       'Knox cou

In [54]:
df.drop('Q5: STATE, PROVINCE, COUNTY, ETC',axis=1,inplace=True)

### 10 - clean ` Q6` columns
>- tip : Q6 has all kinds of chocolate bars and questions with three distinct options to choose from (Joy, Meh, Despair).
- so all the column that has Q6 is a candy name , so you should go through all these column and you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [55]:
# To deal with them all
Q6 = df.loc[:,[x for x in df.columns if 'Q6' in x]].copy()
Q6.fillna('MEH',inplace = True)

In [56]:
# To know the most loved
Q6.replace({"JOY": 1, "MEH" : 0, "DESPAIR" : -1},inplace = True)
best = Q6.sum().sort_values(ascending = False).head(10)
best # The 10 most loved

Q6 | Any full-sized candy bar                1542
Q6 | Reese’s Peanut Butter Cups              1403
Q6 | Kit Kat                                 1395
Q6 | Cash, or other forms of legal tender    1374
Q6 | Twix                                    1342
Q6 | Snickers                                1320
Q6 | Tolberone something or other            1236
Q6 | Lindt Truffle                           1179
Q6 | Peanut M&M’s                            1170
Q6 | Nestle Crunch                           1086
dtype: int64

In [62]:
worst = Q6.sum().sort_values(ascending = True).head(10)
worst # the 10 most hated

Q6 | Broken glow stick                                                        -1601
Q6 | Gum from baseball cards                                                  -1418
Q6 | White Bread                                                              -1411
Q6 | Real Housewives of Orange County Season 9 Blue-Ray                       -1389
Q6 | Dental paraphenalia                                                      -1342
Q6 | Kale smoothie                                                            -1327
Q6 | Candy that is clearly just the stuff given out for free at restaurants   -1286
Q6 | Whole Wheat anything                                                     -1172
Q6 | Creepy Religious comics/Chick Tracts                                     -1160
Q6 | Those odd marshmallow circus peanut things                               -1063
dtype: int64

### 11 - clean ` dress` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [74]:
df["Q10: DRESS"].value_counts()
df["Q10: DRESS"].isna().sum()
df["Q10: DRESS"].fillna("other")

0                other
1       White and gold
2                other
3       White and gold
4       White and gold
             ...      
2455    White and gold
2456    Blue and black
2457    Blue and black
2458             other
2459    White and gold
Name: Q10: DRESS, Length: 2460, dtype: object

### 12 - clean ` day` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [72]:
df["Q11: DAY"].value_counts()
df["Q11: DAY"].fillna("Friday")

0       Friday
1       Sunday
2       Friday
3       Sunday
4       Friday
         ...  
2455    Friday
2456    Friday
2457    Friday
2458    Friday
2459    Sunday
Name: Q11: DAY, Length: 2460, dtype: object

### 13 - check
> after finish cleaning you should make sure your data is clean and that :
- there is no wrong data type
- there is no NaN values
- all the column are cleaing and ready for the next step `EDA`

### 14 - write a summary about all the cleaning steps

In [75]:
# I had a quick overview of the data using .head()
# then i dropped the useless columns
# I cleaned the Going out columns by using unknown in fillna()
# The age column had a lot of wrong data so i dropped them all, convert the data type of the column to numeric and replace the nan values with median
# The country column was full of wrong data and the FuzzyWuzzy couldn't work so i solve the problem manual and summarize all the values to 8 values
# The area column : i think we will not use it so i dropped it
# The Q6 columns : I contains them all in one called Q6 to deal with them all, I replace the values of joy,meh,... to 1 , 0 and -1 to output the 10 most loved and 10 most hated
# although i fillna with meh (0) so that it can't affect
# The Dress column : i fillna with unkown
# The day column : i fillna with the mode(Friday)